# Generated by Django 5.2.3 on 2025-10-21 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='id_paid',
            new_name='is_paid',
        ),
    ]
