# Generated by Django 5.2.3 on 2025-08-23 17:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0007_alter_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date(2025, 8, 23), verbose_name='تاریخ ثبت'),
            preserve_default=False,
        ),
    ]
