# Generated by Django 5.2.3 on 2025-08-27 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0009_articlecomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecomment',
            options={'verbose_name': 'نظر مقاله', 'verbose_name_plural': 'نظرات مقاله'},
        ),
    ]
